backend:
  name: git-gateway
  branch: main

site_url: https://wag3care.netlify.app

media_folder: "images"
public_folder: "/images"

collections:
  - name: "configuracoes"
    label: "Configurações do Site"
    delete: false
    editor:
      preview: false
    files:
      - file: "dados.json"
        label: "Dados Gerais"
        name: "dados"
        fields:
          - label: "Texto da Promoção"
            name: "promocao"
            widget: "string"
            required: false
          - label: "Fotos do Carrossel"
            name: "fotos_carrossel"
            widget: "list"
            required: false
            field:
              label: "Imagem"
              name: "imagem"
              widget: "image"
          - label: "Datas Indisponíveis"
            name: "datas_bloqueadas"
            widget: "list"
            required: false
            field:
              label: "Data (AAAA-MM-DD)"
              name: "data"
              widget: "string"
